[package]
name = "pickle"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
sass-rs = "0.2"
templar = { path = "../templar" }
docopt = "0.8"

[lib]
doc = false

[[bin]]
name = "pickle"
doc = false
